DROP SEQUENCE MYNOSEQ;
DROP TABLE MYBOARD;

CREATE SEQUENCE MYNOSEQ;
CREATE TABLE MYBOARD(
	MYNO NUMBER 				PRIMARY KEY,
	MYNAME VARCHAR2(1000) 		NOT NULL,
	MYTITLE VARCHAR2(2000) 		NOT NULL,
	MYCONTENT VARCHAR2(4000) 	NOT NULL,
	MYDATE DATE 				NOT NULL
);

INSERT INTO MYBOARD VALUES(MYNOSEQ.NEXTVAL,'관리자','스프링 테스트','spring mvc 어렵다',SYSDATE);

SELECT * FROM MYBOARD;


-----------------------------------------------------------------------------------
DROP SEQUENCE MEMBERSEQ;
DROP TABLE MYMEMBER;
CREATE SEQUENCE MEMBERSEQ;
CREATE TABLE MYMEMBER(
	MEMBERNO NUMBER PRIMARY KEY,
	MEMBERID VARCHAR2(1000) NOT NULL,
	MEMBERPW VARCHAR2(1000) NOT NULL,
	MEMBERNAME VARCHAR2(1000) NOT NULL


);

INSERT INTO MYMEMBER
VALUES(MEMBERSEQ.NEXTVAL, 'admin','1234','관리자');

INSERT INTO MYMEMBER
VALUES(MEMBERSEQ.NEXTVAL, 'kh','kh','일반');



SELECT MEMBERNO, MEMBERID, MEMBERPW, MEMBERNAME
FROM MYMEMBER;

SELECT * FROM MYMEMBER;


SELECT * FROM MYMYBOARD;

DROP TABLE TESTBOARD;
DROP SEQUENCE TESTSEQ;

CREATE SEQUENCE TESTSEQ;
CREATE TABLE TESTBOARD(
	MYNO NUMBER 				PRIMARY KEY,
	MYNAME VARCHAR2(1000) 		NOT NULL,
	MYTITLE VARCHAR2(2000) 		NOT NULL,
	MYCONTENT VARCHAR2(4000) 	NOT NULL,
	MYPATH VARCHAR2(200) 		NOT NULL,
	MYPREMIUM VARCHAR2(2)		NOT NULL,
	
	CONSTRAINT TEST_CHK CHECK(MYPREMIUM IN ('Y', 'N'))
);

ALTER TABLE TESTBOARD ADD(MYADDRESS VARCHAR2(500));

INSERT INTO TESTBOARD VALUES(TESTSEQ.NEXTVAL,'김동주','이천은 비싸냐','이천은 싸다','resources/user/img/test/sokcho.JPG','N','이천시');
INSERT INTO TESTBOARD VALUES(TESTSEQ.NEXTVAL,'김송주','강남은 비싸냐','강남은 제일 싸다','resources/user/img/test/sokcho.JPG','N','강남1');
INSERT INTO TESTBOARD VALUES(TESTSEQ.NEXTVAL,'김소주','의정부?','의정부는 비쌈','resources/user/img/test/sokcho.JPG','N','강남2');
DELETE FROM TESTBOARD;
SELECT * FROM TESTBOARD;

select * from testboard 
  		where myaddress like '%강남%';


