DROP SEQUENCE MYNOSEQ;
DROP TABLE MYBOARD;

CREATE SEQUENCE MYNOSEQ;
CREATE TABLE MYBOARD(
	MYNO NUMBER 				PRIMARY KEY,
	MYNAME VARCHAR2(1000) 		NOT NULL,
	MYTITLE VARCHAR2(2000) 		NOT NULL,
	MYCONTENT VARCHAR2(4000) 	NOT NULL,
	MYDATE DATE 				NOT NULL
);

INSERT INTO MYBOARD VALUES(MYNOSEQ.NEXTVAL,'관리자','스프링 테스트','spring mvc 어렵다',SYSDATE);

SELECT * FROM MYBOARD;


-----------------------------------------------------------------------------------
DROP SEQUENCE MEMBERSEQ;
DROP TABLE MYMEMBER;
CREATE SEQUENCE MEMBERSEQ;
CREATE TABLE MYMEMBER(
	MEMBERNO NUMBER PRIMARY KEY,
	MEMBERID VARCHAR2(1000) NOT NULL,
	MEMBERPW VARCHAR2(1000) NOT NULL,
	MEMBERNAME VARCHAR2(1000) NOT NULL


);

INSERT INTO MYMEMBER
VALUES(MEMBERSEQ.NEXTVAL, 'admin','1234','관리자');

INSERT INTO MYMEMBER
VALUES(MEMBERSEQ.NEXTVAL, 'kh','kh','일반');



SELECT MEMBERNO, MEMBERID, MEMBERPW, MEMBERNAME
FROM MYMEMBER;

SELECT * FROM MYMEMBER;


SELECT * FROM MYMYBOARD;

DROP TABLE TESTBOARD;
DROP SEQUENCE TESTSEQ;

CREATE SEQUENCE TESTSEQ;
CREATE TABLE TESTBOARD(
	MYNO NUMBER 				PRIMARY KEY,
	MYNAME VARCHAR2(1000) 		NOT NULL,
	MYTITLE VARCHAR2(2000) 		NOT NULL,
	MYCONTENT VARCHAR2(4000) 	NOT NULL,
	MYPATH VARCHAR2(200) 		NOT NULL,
	MYPREMIUM VARCHAR2(2)		NOT NULL,
	
	CONSTRAINT TEST_CHK CHECK(MYPREMIUM IN ('Y', 'N'))
);

INSERT INTO TESTBOARD VALUES(TESTSEQ.NEXTVAL,'김동주','이천은 비싸냐','이천은 싸다',' ','N');
DELETE FROM TESTBOARD;
SELECT * FROM TESTBOARD;





-----------------------------------------------------------------------------------

DROP TABLE USER_TB;
CREATE TABLE USER_TB
(
    SEQ            INT         NOT NULL, 
    EMAIL          VARCHAR2(100)    NOT NULL, 
    NAME           VARCHAR2(10)    NOT NULL, 
    PWD            VARCHAR2(20)    NOT NULL, 
    PHONE          VARCHAR2(20)    NOT NULL, 
    USERROLE       VARCHAR2(10)    NOT NULL, 
    FILEPATH       VARCHAR2(1000)    NULL, 
    CONFIRM        VARCHAR2(2)    NOT NULL, 
    CLEAN          VARCHAR2(2)    NULL, 
    LIFESTYLE      VARCHAR2(2)    NULL, 
    SHOWER         VARCHAR2(2)    NULL, 
    FAVORITEAGE    VARCHAR2(2)    NULL, 
    GENDER         VARCHAR2(2)    NULL, 
    ANIMAL         VARCHAR2(2)    NULL, 
    NEEDS          VARCHAR2(20)    NULL, 
    CONSTRAINT USER_TB_PK PRIMARY KEY (EMAIL)
);

INSERT INTO USER_TB VALUES(
	1,
	'michaelhj@naver.com',
	'곽',
	'123',
	'01039107929' ,
	'USER',
	NULL,
	'Y',
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL
);
INSERT INTO USER_TB VALUES(
	3,
	'missdla4929@naver.com',
	'임미경',
	'10041004',
	'01071164929' ,
	'AGENT',
	NULL,
	'Y',
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL,
	NULL
);
SELECT * FROM USER_TB;

DROP TABLE ROOM_TB;
DROP SEQUENCE ROOMSEQ;
CREATE SEQUENCE ROOMSEQ;
CREATE TABLE ROOM_TB
(
    NO_RM           NUMBER    NOT NULL,  -- 방번호
    EMAIL           VARCHAR2(100)    NOT NULL REFERENCES USER_TB(EMAIL) ON DELETE CASCADE, 
    PHONE_RM        VARCHAR2(20)    NULL, 
    AGTNAME_RM      VARCHAR2(100)    NOT NULL, 
    PLUSYN_RM       VARCHAR2(2)    NOT NULL, 
    TITLE_RM        VARCHAR2(1000)    NOT NULL, 	-- 크기너무작다ㅠ 1000으로 늘리기
    PICTURE_RM      VARCHAR2(1000)    NOT NULL, 
    ANIMAL_RM       VARCHAR2(20)    NOT NULL, 
    ELEVATOR_RM     VARCHAR2(2)    NOT NULL, 
    VERANDA_RM      VARCHAR2(2)    NOT NULL, 
    ROOMIN_RM       DATE    	   NOT NULL, 
    CONTENT_RM      VARCHAR2(2000)    NOT NULL, 
    AIRCON_RM       VARCHAR2(10)    NULL, 
    WASHER_RM       VARCHAR2(2)    NULL,
    GASRANGE_RM		VARCHAR2(2)	   NULL,
    INDUCTION_RM	VARCHAR2(2)	   NULL,
    DESK_RM         VARCHAR2(2)    NULL, 
    TV_RM           VARCHAR2(2)    NULL, 
    REF_RM          VARCHAR2(2)    NULL, 
    BED_RM          VARCHAR2(2)    NULL, 
    SHOWHOUSE_RM    VARCHAR2(2)    NULL, 
    CLOSET_RM       VARCHAR2(2)    NULL, 
    MICROWAVE_RM    VARCHAR2(2)    NULL,
    SINK_RM			VARCHAR2(2)	   NULL,
    RENT_RM         VARCHAR2(10)    NOT NULL, 
    ROOMPRICE_RM    VARCHAR2(100)   NOT NULL, 
    EXPENSE_RM      VARCHAR2(50)   NOT NULL, 
    ROOMTYPE_RM     VARCHAR2(50)   NOT NULL, 
    ADDR_RM         VARCHAR2(100)    NOT NULL, 
    ADDR_DT_RM      VARCHAR2(100)    NOT NULL, 
    ROOMSIZE_RM     VARCHAR2(20)    NOT NULL, 
    ROOMSIZE2_RM    VARCHAR2(20)    NOT NULL, 
    FLOOR_RM        VARCHAR2(20)    NOT NULL, 
    FLOOR2_RM       VARCHAR2(20)    NOT NULL, 
    PARKING_RM      VARCHAR2(2)    NULL, 
    CONSTRAINT ROOM_TB_PK PRIMARY KEY (NO_RM)
);
--    HEAT_RM         VARCHAR2(10)    NOT NULL, 
--    BUILTIN_RM      VARCHAR2(2)    NOT NULL, 		



INSERT INTO ROOM_TB VALUES
(
    12,
    'missdla4929@naver.com', 
    NULL,
    'feel중개사',
    'Y',
    '제목제목제목',
    'FILEPATH+FILENAME',
    'Y',
    'Y',
    'Y',
    'Y',
    'Y',
    '20200331',
    '좋은집입니다', 
    NULL,
    NULL,
    NULL,
    NULL,
    NULL, 
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    '월세',
    '500/30',
    '10',
    '원룸',
    '광주시',
    '경기광주역',
    '20',
    '18',
    '4',
    '3', 
    'N'
);
SELECT * FROM ROOM_TB;

DELETE FROM ROOM_TB WHERE NO_RM=1;



DROP TABLE USERFAVORITE_TB;
CREATE TABLE USERFAVORITE_TB
(
    EMAIL        VARCHAR2(100)    NOT NULL REFERENCES USER_TB(EMAIL) ON DELETE CASCADE, 
    RECENT_FV    NUMBER    NULL,
    DIBS_FV      NUMBER    NULL,   
    DATE_FV		 DATE	   NOT NULL,
    ROOM_EX		 VARCHAR2(2) NOT NULL
);

INSERT INTO USERFAVORITE_TB VALUES
(
	'michaelhj@naver1.com',
	1,
	NULL,
	SYSDATE,
	'Y'
);
SELECT * FROM USERFAVORITE_TB;
SELECT COUNT(RECENT_FV)
		  FROM USERFAVORITE_TB
		 WHERE EMAIL ='michaelhj@naver.com';
DELETE FROM USERFAVORITE_TB WHERE EMAIL='michaelhj@naver.com';


DROP TABLE SEARCH_TB;
CREATE SEQUENCE SEQ_SHSEQ;
CREATE TABLE SEARCH_TB
(
	SEQ_SH		  NUMBER      NOT NULL,
    EMAIL         VARCHAR2(100)        NOT NULL REFERENCES USER_TB(EMAIL) ON DELETE CASCADE, 
    CONTENT_SH    VARCHAR2(50)    NOT NULL, 
    DATE_SH       DATE            NOT NULL,
    CONSTRAINT SEARCH_TB_PK PRIMARY KEY (SEQ_SH)
);

INSERT  INTO SEARCH_TB VALUES 
(	
	SEQ_SHSEQ.NEXTVAL,
	'michaelhj@naver.com', -- 첫줄 공백 X
	'이천시9',
	SYSDATE
);

SELECT EMAIL, CONTENT_SH
	FROM SEARCH_TB
	WHERE EMAIL='michaelhj@naver.com'
	ORDER BY DATE_SH DESC;

SELECT SEQ_SH, EMAIL,
		   CONTENT_SH
	FROM (
	SELECT SEQ_SH, EMAIL, CONTENT_SH
	FROM SEARCH_TB
	WHERE EMAIL='michaelhj@naver.com'
	ORDER BY DATE_SH DESC
	)
	WHERE ROWNUM <= 5;	  

DROP TABLE NOTICE_TB;
CREATE SEQUENCE SEQ_NT_SEQ;
CREATE TABLE NOTICE_TB
(
    SEQ_NT        INT             NOT NULL, 
    TITLE_NT      VARCHAR2(100)    NOT NULL, 
    CONTENT_NT    VARCHAR2(3000)    NOT NULL, 
    DATE_NT       DATE            NOT NULL, 
    CONSTRAINT NOTICE_TB_PK PRIMARY KEY (SEQ_NT)
);




-- reivew table
DROP TABLE REVIEW_TB;
CREATE TABLE REVIEW_TB
(
    EMAIL       VARCHAR2(100)    NOT NULL, 
    AGEMAIL     VARCHAR2(100)    NOT NULL REFERENCES USER_TB(EMAIL) ON DELETE CASCADE, 
    RCONTENT    VARCHAR2(300)    NOT NULL,
    STAR        NUMBER    NOT NULL,
    RDATE		DATE 	  NOT NULL,
    CONSTRAINT REVIEW_TB_PK PRIMARY KEY (EMAIL,AGEMAIL)
);
INSERT INTO REVIEW_TB VALUES
(
	'michaelhj@naver.com',
	'michaelhj@naver2.com',
	'별로',
	4.5,
	SYSDATE
);

SELECT * FROM REVIEW_TB;



		SELECT TITLE_RM,PICTURE_RM,PLUSYN_RM,ROOMTYPE_RM,ROOMPRICE_RM,FLOOR_RM,ROOMSIZE_RM,EXPENSE_RM
		FROM ROOM_TB
		ORDER BY NO_RM DESC




		SELECT COUNT(NO_RM)
			FROM ROOM_TB
			WHERE NO_RM > 0 AND EMAIL='missdla4929@naver.com';





