DROP TABLE QNA_TB;
DROP SEQUENCE SEQ_QSEQ;

CREATE SEQUENCE SEQ_QSEQ;
CREATE TABLE QNA_TB
(
    SEQ_Q         NUMBER        NOT NULL, 
    GROUPSEQ_Q    NUMBER    NOT NULL, 
    ORDER_Q       NUMBER    NOT NULL, 
    TITLET_Q      VARCHAR2(5)    NOT NULL, 
    TITLE_Q       VARCHAR2(40)    NOT NULL, 
    CONTENT_Q     VARCHAR2(1000)    NOT NULL, 
    EMAIL         VARCHAR2(100)    NOT NULL, 
    DATE_Q        DATE        NOT NULL, 
    CONSTRAINT QNA_TB_PK PRIMARY KEY (SEQ_Q)
);

-- 파일업로드  테이블
CREATE TABLE TB_FILE
(
  IDX   NUMBER,
  BOARD_IDX NUMBER NOT NULL,
  ORIGINAL_FILE_NAME VARCHAR2(260 BYTE) NOT NULL,
  STORED_FILE_NAME VARCHAR2(36 BYTE) NOT NULL,
  FILE_SIZE NUMBER,
  CREA_DTM  DATE DEFAULT SYSDATE NOT NULL,
  CREA_ID   VARCHAR2(30 BYTE) NOT NULL,
  DEL_GB    VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL,
  PRIMARY KEY (IDX)
);
-- 파일업로드 테이블
CREATE SEQUENCE SEQ_TB_FILE_IDX START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCACHE;
DROP TABLE TB_FILE;
DROP SEQUENCE SEQ_TB_FILE_IDX;


SELECT * FROM QNA_TB;


INSERT INTO QNA_TB VALUES(SEQ_QSEQ.NEXTVAL,1,1,'U','TITLE','HAPPY','USER01',SYSDATE);
INSERT INTO QNA_TB VALUES(SEQ_QSEQ.NEXTVAL,1,2,'U','TITLE','HAPPY','USER01',SYSDATE); 

